baseURL = 'https://micro-frontends.tuando.net/'
languageCode = 'en-us'
title = 'Micro frontends'
theme = "book"

# Book configuration
disablePathToLower = true
enableGitInfo = true

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[menu]
[[menu.after]]
  name = "Github"
  url = "https://github.com/dotuan9x/micro-frontends"
  weight = 10

[params]
    BookSearch = true

    # Set source repository location.
    # Used for 'Last Modified' and 'Edit this page' links.
    BookRepo = 'https://github.com/dotuan9x/micro-frontends'